# =========================================================================== #
#	DEVELOPMENT
# =========================================================================== #

## run/api: run the cmd/api application
.PHONY: run/api
run/api:
	@go run ./cmd/api


.PHONY: connect/db
connect/db:
	@psql $$GHOSTPLANET_DB_DSN